### ISSUE TITLE
No information on the expected environment architecture and required systems

### ISSUE THREAD

**Issue by scoussens** [Cireson/composed-smp-rs-sql#1]
We need something in here about what we expect the architecture in the lab environment to look like. Right now, there isn't really any mention that we expect you to have a VM on the domain with docker installed, that is going to be the actual container host. 

Most people are going to have docker installed locally, and it sounds like this would be an issue?

@jjburr

**Comment by jjburr** [comment]
Have updated this now with a diagram and further notes @scoussens
